### ISSUE TITLE
Unicode characters not supported by rxvt-unicode with Noto Sans Mono fonts

### ISSUE THREAD

**Issue by fturco** [subdavis/kobo-book-downloader#22]
When running the `kobodl book list`, it correctly lists all my Kobo e-books, but it also shows placeholders (boxes) instead of some intended Unicode symbol (emoji?). Basically the two columns between "RevisionId" and "Owner" are unreadable with my choice of terminal emulator.

By the way, I use rxvt-unicode with the Noto Sans Mono font.
I also tried to add the Noto Emoji font to rxvt-unicode configuration, without success.

Is there some other font I can try?
Should those characters be replaced by descriptive strings instead?

**Comment by subdavis** [comment]
Could you paste a screenshot?  The boxes you see might be intentional: they could be empty checkboxes

![Screenshot from 2020-07-20 13-06-25](https://user-images.githubusercontent.com/4214172/87965511-da4c8680-ca89-11ea-9d40-82df5bf049a8.png)

Agree that it's bad UX, I'll try to do something different.

**Comment by fturco** [comment]
![kobodl](https://user-images.githubusercontent.com/5459866/87969378-5236a300-cac2-11ea-9f77-9b15aafd7572.png)

**Comment by subdavis** [comment]
Alright well I guess I'll just go back to ascii.

Thanks

**Comment by subdavis** [comment]
Resolved in 0.4.1.  Kept the emoji, but added plain text along side so that you can still tell.
