### ISSUE TITLE
Captcha retrieval doesn't work

### ISSUE THREAD

**Issue by 17721** [subdavis/kobo-book-downloader#55]
I tried 3 different browsers in incognito mode and I get the same error everywhere:

<img width="803" alt="Capture" src="https://user-images.githubusercontent.com/50483092/133857417-af80dc69-8a96-48c5-9b64-03579e34c2f8.PNG">

**Comment by subdavis** [comment]
1) Cannot reproduce
2) You erased the issue template.  Don't do that.  I wrote it for a reason, because
3) You clearly have an outdated version of `kobodl` (by a lot).  Please upgrade.

Please go read the thing you erased: https://github.com/subdavis/kobo-book-downloader/blob/main/.github/ISSUE_TEMPLATE/issue-report.md
